### ISSUE TITLE
Adding functions for preference settings and displaying recent files.

### ISSUE THREAD

**Issue by scienceasdf** [JosanSun/textEditor#2]
I think the next step is to add the two functions. Both are storaged in a json file in the local folder.

**Comment by scienceasdf** [comment]
I'm just a beginner in programming. So all are up to you, Mr Sun. Hope you never mind me an idol taking part in this project.

**Comment by JosanSun** [comment]
Oh! Thank you for your participation in the project. Your advice is really helpful. Displaying recent files is one of my wantted functions. Let's do it!

**Comment by JosanSun** [comment]
@scienceasdf  I have try to use the singal and slot to fix the closeEvent() bug.

And diaplaying asterisk issue will smoothly sloved by isWindowModified() detection. Thank you for your inspiration. ::smile::
